"""Orion plaintext encoding wrappers for compact GQA encodings.

This file calls the plaintext encoding code to generate NumPy slot vectors,
pads them to the Orion slot count, converts them to PyTorch tensors,
then encodes those tensors into Orion plaintexts once.

Important:
    - Inputs/weights are generated by plaintext.encoding as NumPy vectors.
    - Orion expects PyTorch tensors for encode().
    - These are plaintext weights, so we encode but do NOT encrypt them.
"""

from __future__ import annotations

from typing import Any, Optional
import torch
import orion

from ..plaintext.dims import GQADims
from ..plaintext.encoding import make_weights_q_gqa, make_weights_kv


def encode_plain_vector(
    vec: np.ndarray,
    *,
    n_he: int,
    level: int,
) -> Any:
    """Zero-pad one slot vector to n_he and encode it as an Orion plaintext."""
    t = torch.as_tensor(vec, dtype=torch.float64).reshape(-1)

    if t.numel() > n_he:
        raise ValueError(
            f"Cannot encode vector of length {t.numel()}; n_he={n_he} slots."
        )

    padded = torch.zeros(n_he, dtype=torch.float64)
    padded[: t.numel()] = t
 
    return orion.encode(padded, level)


 
def encode_plain_list(vecs: List[Any], *, n_he: int, level: int) -> List[Any]:
    """Encode a flat list of slot vectors into Orion plaintexts."""
    return [encode_plain_vector(v, n_he=n_he, level=level) for v in vecs]


def encode_plain_nested_list(
    vecs: List[List[Any]], *, n_he: int, level: int
) -> List[List[Any]]:
    """Encode a nested list of slot vectors into Orion plaintexts.
 
    Used for Q weights, where the plaintext encoding returns groups of vectors.
    """
    return [
        [encode_plain_vector(v, n_he=n_he, level=level) for v in group]
        for group in vecs
    ]


def make_he_weights_q_gqa(dims: GQADims, *, seed: int = 1, n_he: int, level: int):
    """Generate raw Wq and Orion-encoded compact Q weight plaintexts.
 
    Returns:
        Wq_raw:
            Raw weight matrix, used for reference checking.
        Wq_enc_list:
            Nested list of Orion plaintexts, ready for ct-pt multiplication
            against ciphertexts at `level`.
    """
    Wq_raw, Wq_enc_list_raw = make_weights_q_gqa(dims, seed=seed)
    Wq_enc_list = encode_plain_nested_list(Wq_enc_list_raw, n_he=n_he, level=level)
    return Wq_raw, Wq_enc_list
 


 
def make_he_weights_kv(dims: GQADims, *, seed: int = 1, n_he: int, level: int):
    """Generate raw Wk/Wv and Orion-encoded compact K/V weight plaintexts.
 
    Returns:
        W_raw:
            Raw weight matrix, used for reference checking.
        W_enc:
            Flat list of Orion plaintexts, ready for ct-pt multiplication
            against ciphertexts at `level`.
    """
    W_raw, W_enc_raw = make_weights_kv(dims, seed=seed)
    W_enc = encode_plain_list(W_enc_raw, n_he=n_he, level=level)
    return W_raw, W_enc