"""Orion plaintext encoding wrappers for compact GQA encodings.

This file calls the plaintext encoding code to generate PyTorch slot
vectors, zero-pads them to the Orion slot count, then encodes them into
Orion plaintexts once.

Important:
    - Inputs/weights are generated by plaintext.encoding as PyTorch tensors.
    - These are plaintext weights, so we encode but do NOT encrypt them.
"""

from __future__ import annotations

from typing import Any, List, Optional
import torch
import orion

from ..plaintext.dims import GQADims
from ..plaintext.encoding import (
    make_weights_q_gqa,
    make_weights_kv,
    make_sparse_input_kv,
    gqa_lane_offsets,
)
from ..plaintext.counter import counter
from .he_ops_orion import encode_pt


def encode_plain_vector(
    vec: torch.Tensor,
    *,
    n_he: int,
    level: int,
) -> Any:
    """Zero-pad one slot vector to n_he and encode it as an Orion plaintext."""
    t = torch.as_tensor(vec, dtype=torch.float64).reshape(-1)

    if t.numel() > n_he:
        raise ValueError(
            f"Cannot encode vector of length {t.numel()}; n_he={n_he} slots."
        )

    padded = torch.zeros(n_he, dtype=torch.float64)
    padded[: t.numel()] = t
 
    return orion.encode(padded, level)


 
def encode_plain_list(vecs: List[Any], *, n_he: int, level: int) -> List[Any]:
    """Encode a flat list of slot vectors into Orion plaintexts."""
    return [encode_plain_vector(v, n_he=n_he, level=level) for v in vecs]


def encode_plain_nested_list(
    vecs: List[List[Any]], *, n_he: int, level: int
) -> List[List[Any]]:
    """Encode a nested list of slot vectors into Orion plaintexts.
    """
    return [
        [encode_plain_vector(v, n_he=n_he, level=level) for v in group]
        for group in vecs
    ]


def decrypt_decode_ct(ct: Any) -> torch.Tensor:
    """Client side: decrypt and decode one Orion ciphertext to a torch tensor."""
    return torch.as_tensor(ct.decrypt().decode(), dtype=torch.float64)


def decrypt_decode_nested(obj: Any) -> Any:
    """Decrypt/decode nested lists of ciphertexts; useful for verification."""
    if isinstance(obj, list):
        return [decrypt_decode_nested(x) for x in obj]
    if isinstance(obj, tuple):
        return tuple(decrypt_decode_nested(x) for x in obj)
    return decrypt_decode_ct(obj)


def encrypt_sparse_input_kv(x: torch.Tensor, dims: GQADims, *, level: int) -> List[Any]:
    """Client-side: pack x into sparse GQA slots and encrypt each chunk."""
    sparse_plain = make_sparse_input_kv(x, dims)
    return [orion.encrypt(encode_pt(v, level)) for v in sparse_plain]


def expand_sparse_input_kv_he(sparse_cts: List[Any], dims: GQADims) -> List[Any]:
    """Ciphertext version of expand_sparse_input_kv_plain."""
    lane_offsets = gqa_lane_offsets(dims)
    chunks: List[Any] = []

    for sparse_ct in sparse_cts:
        for start in range(0, dims.d_kv, dims.t_p):
            offsets = lane_offsets[start : start + dims.t_p]
            acc = None
            for lane, off in enumerate(offsets):
                shift = off * dims.t_p - lane

                if shift == 0:
                    term = sparse_ct
                else:
                    term = sparse_ct.roll(shift)
                    counter.rotations += 1

                acc = term if acc is None else acc + term

            chunks.append(acc)
    return chunks


def make_he_weights_q_gqa(dims: GQADims, *, seed: int = 1, n_he: int, level: int):
    """Generate raw Wq and Orion-encoded compact Q weight plaintexts.

    Returns:
        Wq_raw:
            Raw weight matrix, used for reference checking.
        Wq_enc_list:
            Nested list of Orion plaintexts, ready for ct-pt multiplication
            against ciphertexts at `level`.
        Wq_enc_list_raw:
            Nested list of plain torch chunks (pre-Orion-encoding), usable
            directly with `plaintext.ops.vmm_kv` for plaintext-domain
            computation (e.g. a fast plaintext prefill pass).
    """
    Wq_raw, Wq_enc_list_raw = make_weights_q_gqa(dims, seed=seed)
    Wq_enc_list = encode_plain_nested_list(Wq_enc_list_raw, n_he=n_he, level=level)
    return Wq_raw, Wq_enc_list, Wq_enc_list_raw



 
def make_he_weights_kv(dims: GQADims, *, seed: int = 1, n_he: int, level: int):
    """Generate raw Wk/Wv and Orion-encoded compact K/V weight plaintexts.

    Returns:
        W_raw:
            Raw weight matrix, used for reference checking.
        W_enc:
            Flat list of Orion plaintexts, ready for ct-pt multiplication
            against ciphertexts at `level`.
        W_enc_raw:
            Flat list of plain torch chunks (pre-Orion-encoding), usable
            directly with `plaintext.ops.vmm_kv` for plaintext-domain
            computation (e.g. a fast plaintext prefill pass).
    """
    W_raw, W_enc_raw = make_weights_kv(dims, seed=seed)
    W_enc = encode_plain_list(W_enc_raw, n_he=n_he, level=level)
    return W_raw, W_enc, W_enc_raw